basePath: /
definitions:
  github_com_gulizay91_template-go-api_internal_models.Message:
    properties:
      body:
        example: '{"message": "template message body"}'
        type: string
    type: object
  github_com_gulizay91_template-go-api_internal_models.Template:
    properties:
      id:
        type: integer
      message:
        type: string
      name:
        type: string
    type: object
info:
  contact:
    email: gulizay91@gmail.com
    name: Güliz AY
    url: https://github.com/gulizay91
  description: Template Go Api - RESTful
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
  termsOfService: https://swagger.io/terms/
  title: Template Go API
  version: "1.0"
paths:
  /api/v1/template:
    get:
      consumes:
      - '*/*'
      description: get template
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/github_com_gulizay91_template-go-api_internal_models.Template'
            type: array
      summary: get template
      tags:
      - templates
  /api/v1/template/message:
    post:
      consumes:
      - application/json
      description: send message to rabbitmq queue
      parameters:
      - description: Message
        in: body
        name: message
        required: true
        schema:
          $ref: '#/definitions/github_com_gulizay91_template-go-api_internal_models.Message'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: send template message
      tags:
      - templates
  /health:
    get:
      consumes:
      - '*/*'
      description: get the status of server.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Show the status of server.
      tags:
      - root
  /ready:
    get:
      consumes:
      - '*/*'
      description: get the status of server.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Show the status of server.
      tags:
      - root
schemes:
- http
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Bearer-Token
    type: apiKey
swagger: "2.0"
